SELECT TOP (1000) [Id]
      ,[Firstname]
      ,[Lastname]
      ,[CollegeName]
      ,[PhoneNumber]
      ,[Email]
      ,[Address]
      ,[course]
      ,[createdBy]
      ,[createdDate]
      ,[updatedBy]
      ,[updatedDate]
      ,[isDeleted]
  FROM [BITech].[dbo].[Interns] where ID in (6,7,8,9,10);
