SELECT TOP (1000) [Id]
      ,[FirstName]
      ,[LastName]
      ,[CollegeName]
      ,[PhoneNo]
      ,[Email]
      ,[Address]
      ,[Course]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[IsDeleted]
  FROM [BITECH].[dbo].[Interns] where id in (6,7,8,9,10);
