use BITECH
go
--CREATE table Employee
--(
--Id int Identity(1,1) primary key,
--FirstName varchar(max) NOT NULL,
--LastName varchar(max)NOT NULL,
--[Role] Varchar(25)NOT NULL,
--PhoneNO varchar(13) NOT NULL,
--Email Varchar(25)NOT NULL,
--[Address] varchar(max),
--Salary decimal(18,4)NOT NULL,
--CreatedBy varchar(max)NOT NULL,
--CreatedDate DateTime NOT NULL,
--ModifiedBy varchar(max) NOT NULL,
--ModifiedDate DateTime NOT NULL,
--IsDeleted bit NOT NULL
--);

--INSERT INTO Employee(
--    FirstName, LastName, [Role], PhoneNO, Email, [Address],
--    Salary, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy, IsDeleted
--)
--VALUES
--('Srujan', 'Shetty', 'Software Engineer', '555-0101', 'alice.j@bitech.com', '123 Tech Lane, San Francisco, CA', 95000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
--('Archana', 'Acharya', 'Data Analyst', '555-0102', 'bob.smith@bitech.com', '456 Data Drive, Austin, TX', 78000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
--('Murali', 'Davis', 'Project Manager', '555-0103', 'c.davis@bitech.com', '789 Agile Way, Seattle, WA', 105000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
--('Hemanth', 'Prince', 'HR Specialist', '555-0104', 'diana.p@bitech.com', '101 People St, Chicago, IL', 65000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
--('Sankalp', 'Hunt', 'DevOps Engineer', '555-0105', 'e.hunt@bitech.com', '202 Cloud Ave, New York, NY', 115000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0);


--SELECT * FROM EMPLOYEE;
--Truncate table Employee;
--INSERT INTO Employee(
--    FirstName, LastName, [Role], PhoneNO, Email, [Address],
--    Salary, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy, IsDeleted
--)
--VALUES
--('Srujan', 'Shetty', 'Software Engineer', '555-0101', 'alice.j@bitech.com', '123 Tech Lane, San Francisco, CA', 95000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
--('Archana', 'Acharya', 'Data Analyst', '555-0102', 'bob.smith@bitech.com', '456 Data Drive, Austin, TX', 78000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
--('Murali', 'Davis', 'Project Manager', '555-0103', 'c.davis@bitech.com', '789 Agile Way, Seattle, WA', 105000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
--('Hemanth', 'Prince', 'HR Specialist', '555-0104', 'diana.p@bitech.com', '101 People St, Chicago, IL', 65000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
--('Sankalp', 'Hunt', 'DevOps Engineer', '555-0105', 'e.hunt@bitech.com', '202 Cloud Ave, New York, NY', 115000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0);
--SELECT * FROM EMPLOYEE;

--CREATE TABLE MENTOR
--(
-- ID INT IDENTITY(1,1) PRIMARY KEY,
-- EmpID INT NOT NULL,
-- IntID INT NOT NULL,
--CreatedDate  DATETIME      NOT NULL,
--    CreatedBy    NVARCHAR(50)  NOT NULL,
--    ModifiedDate DATETIME      NOT NULL,
--    ModifiedBy   NVARCHAR(50)  NOT NULL,
--    IsDeleted    BIT           NOT NULL
--);
--INSERT INTO Employee(
----    FirstName, LastName, [Role], PhoneNO, Email, [Address],
----    Salary, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy, IsDeleted
----)
----VALUES
----('Srujan', 'Shetty', 'Software Engineer', '555-0101', 'alice.j@bitech.com', '123 Tech Lane, San Francisco, CA', 95000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
----('Archana', 'Acharya', 'Data Analyst', '555-0102', 'bob.smith@bitech.com', '456 Data Drive, Austin, TX', 78000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
----('Murali', 'Davis', 'Project Manager', '555-0103', 'c.davis@bitech.com', '789 Agile Way, Seattle, WA', 105000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
----('Hemanth', 'Prince', 'HR Specialist', '555-0104', 'diana.p@bitech.com', '101 People St, Chicago, IL', 65000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0),
----('Sankalp', 'Hunt', 'DevOps Engineer', '555-0105', 'e.hunt@bitech.com', '202 Cloud Ave, New York, NY', 115000.00, GETDATE(), 'Admin', GETDATE(), 'Admin', 0);
----SELECT * FROM EMPLOYEE;
--INSERT INTO [dbo].[MENTOR]
--    ([EmpID], [IntID], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy], [IsDeleted])
--VALUES
--    (2, 1, GETDATE(), 'ad', GETDATE(), 'ad', 0), (2, 2, GETDATE(), 'ad', GETDATE(), 'ad', 0),
--    (2, 3, GETDATE(), 'ad', GETDATE(), 'ad', 0), (2, 4, GETDATE(), 'ad', GETDATE(), 'ad', 0),
--    (2, 5, GETDATE(), 'ad', GETDATE(), 'ad', 0), (3, 6, GETDATE(), 'ad', GETDATE(), 'ad', 0),
--    (3, 7, GETDATE(), 'ad', GETDATE(), 'ad', 0), (3, 8, GETDATE(), 'ad', GETDATE(), 'ad', 0),
--    (3, 9, GETDATE(), 'ad', GETDATE(), 'ad', 0), (3, 10, GETDATE(), 'ad', GETDATE(), 'ad', 0),
--    (4, 1, GETDATE(), 'ad', GETDATE(), 'ad', 0), (4, 2, GETDATE(), 'ad', GETDATE(), 'ad', 0),
--    (4, 3, GETDATE(), 'ad', GETDATE(), 'ad', 0), (4, 4, GETDATE(), 'ad', GETDATE(), 'ad', 0),
--    (4, 5, GETDATE(), 'ad', GETDATE(), 'ad', 0), (5, 6, GETDATE(), 'ad', GETDATE(), 'ad', 0),
--    (5, 7, GETDATE(), 'ad', GETDATE(), 'ad', 0), (5, 8, GETDATE(), 'ad', GETDATE(), 'ad', 0),
--    (5, 9, GETDATE(), 'ad', GETDATE(), 'ad', 0), (5, 10, GETDATE(), 'ad', GETDATE(), 'ad', 0);
--GO
--Select * From Interns as i;
--select DISTINCT FirstName,LastName from Interns INNER JOIN MENTOR ON MENTOR.IntID=Interns.Id;
--select
--DISTINCT i.FirstName,i.LastName 
--from Interns i
--INNER JOIN MENTOR m ON m.IntID=i.Id
--INNER JOIN 
--Employee e ON e.ID=m.EmpID 
--WHERE 
--e.Id=5;
--select 
--FirstName,Salary]
--from
--Employee
--WHERE Salary>(SELECT AVG(Salary) from Employee);
--UPDATE 
--Employee
--SET Salary=Salary+2000 where IsDeleted=0;


                                                                                                                                                                                             