SELECT TOP (1000) [Id]
      ,[FirstName]
      ,[LastName]
      ,[Role]
      ,[PhoneNo]
      ,[Email]
      ,[Address]
      ,[Salary]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[isDeleted]
  FROM [BITECH].[dbo].[Employee]
