SELECT TOP (1000) [Id]
      ,[Fname]
      ,[Lastname]
      ,[Collegename]
      ,[PhoneNo]
      ,[Email]
      ,[address]
      ,[course]
      ,[CretaedBy]
      ,[CretaedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[isDeleted]
  FROM [BITECH].[dbo].[Interns] WHERE Id IN(1,2,3,4,5)
